apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-nb-taskrun
spec:
  # Use service account with git and image repo credentials
  serviceAccountName: pipeline
  taskRef:
    name: simple-model-s2i
  params:
    - name: BUILDER_IMAGE
      value: quay.io/willbenton/simple-model-s2i:cached-pipeline-s2i
  resources:
    outputs:
      - name: builtImage
        resourceRef:
          name: simple-s2i-built-image