apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-nb-taskrun
spec:
  # Use service account with git and image repo credentials
  serviceAccountName: pipeline
  taskRef:
    name: simple-model-s2i
  inputs:
    params:
    - name: BUILDER_IMAGE
      value: quay.io/willbenton/simple-model-s2i:cached-pipeline-s2i
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/willb/ml-workflows-notebook
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/opendatahub-user1/simple-model-s2i
