apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: simple-s2i-built-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-task-run/pipeline:latest
