apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: simple-model-s2i
spec:
  inputs:
    params:
    - description: The location of the s2i builder image.
      name: BUILDER_IMAGE
	  value: quay.io/willbenton/simple-model-s2i:cached-pipeline-s2i
    - default: .
      description: The location of the path to run s2i from.
      name: PATH_CONTEXT
    - default: 'true'
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      name: TLSVERIFY
    - name: LOGLEVEL
      description: Log level when running the S2I binary
      default: '0'
    - name: S2I_SOURCE_NOTEBOOK_LIST
      default: 03-feature-engineering-tfidf.ipynb,04-model-logistic-regression.ipynb
    resources:
    - name: source
		type: git
		params:
		- name: uri
		  value: https://github.com/willb/openshift-ml-workflows-workshop
		- name: ref
		  value: develop
  outputs:
    resources:
    - name: image
      type: image