apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: simple-model-s2i
spec:
  params:
    - name: BUILDER_IMAGE
      description: The location of the s2i builder image.
    - name: PATH_CONTEXT
      description: The location of the path to run s2i from.
      default: .
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      default: 'false'
    - name: LOGLEVEL
      description: Log level when running the S2I binary
      default: '0'
    - name: S2I_SOURCE_NOTEBOOK_LIST
      default: 03-feature-engineering-tfidf.ipynb,04-model-logistic-regression.ipynb
  resources:
#   inputs:
#     - name: source
#       type: git
    outputs:
      - name: builtImage
        type: image
  steps:
  - command:
    - /usr/local/bin/s2i
    - --loglevel=$(params.LOGLEVEL)
    - build
    - -e S2I_SOURCE_NOTEBOOK_LIST=$(params.S2I_SOURCE_NOTEBOOK_LIST)
    - $(params.PATH_CONTEXT)
    - $(params.BUILDER_IMAGE)
    - --image-scripts-url
    - image:///opt/sms/.s2i/
    - --scripts-url
    - image:///opt/sms/.s2i/
    - --as-dockerfile
    - /gen-source/Dockerfile.gen
    image: quay.io/openshift-pipeline/s2i:nightly
    name: generate
    volumeMounts:
      - mountPath: /gen-source
        name: gen-source
    workingDir: /workspace/source
  - command:
    - buildah
    - bud
    - --tls-verify=$(params.TLSVERIFY)
    - --layers
    - -f
    - /gen-source/Dockerfile.gen
    - -t
    - $(resources.outputs.builtImage.url)
    - .
    image: quay.io/buildah/stable
    name: build
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - mountPath: /gen-source
      name: gen-source
    workingDir: /gen-source
  - command:
    - buildah
    - push
    - --tls-verify=$(params.TLSVERIFY)
    - $(resources.outputs.builtImage.url)
    - docker://$(resources.outputs.builtImage.url)
    image: quay.io/buildah/stable
    name: push
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
  - emptyDir: {}
    name: gen-source
